version: '3'
services:
  web:
    image: chessbuddy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    expose:
      - 80
    restart: always
    environment:
      - SERVER_ADDRESS=0.0.0.0
    networks:
      - chessbuddy
networks:
  chessbuddy:

